[aliases]
test = pytest
[pytest]
rsyncdirs = tests
rsyncignore = tests/tools
markers =
    incremental: for test run ordering, if one test failed then test run is stopped (no needed to proceed).
    functional: Heavy tests, could be with some DB or additional access (required isolated env.).
    regression: Simple tests (checks basic functional of the services- smoke/sanity).
    swagger: Simple tests front of Swagger (checks basic functional of the services- smoke/sanity).
    load: Test iterations with goal to load end-point.
    service: Swagger end point.
    user: Swagger end point.
    desktop: Swagger end point.
    entity_data: Swagger end point.
    entity: Swagger end point.
    role: Swagger end point.
    workspace: Swagger end point.
    workspace_user: Swagger end point.
usefixtures = r_time_count
filterwarnings = ignore::DeprecationWarning
qt_log_level_fail = CRITICAL
qt_log_format = {rec.when} {rec.type_name}: {rec.message}
log_cli = 1
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S
addopts = --verbose
          -p no:warnings
#         -n1
# timeout = 300
python_files = *_test.py
python_functions = test_*
testpaths = tests/*_tests
ENV = {ENV}
env = D:ENV=PROD
