[tox]
minversion = 3.10.0
envlist = py311
[testenv]
usedevelop = true
basepython = python3.11
changedir = tests
passenv = ENV
skip_install = true
deps = -rrequirements.txt
# install_command = pip --proxy {env:HTTP_PROXY} install {opts} {packages}
install_command = pip install {opts} {packages}
commands = python -m pytest {posargs}
